apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smart-attendance-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.smartattendance.local
      secretName: smart-attendance-tls
  rules:
    - host: api.smartattendance.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
