apiVersion: v1
kind: Secret
metadata:
  name: smart-attendance-secret
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbCthc3luY3BnOi8vdXNlcjpwYXNzd29yZEBwb3N0Z3Jlczo1NDMyL2F0dGVuZGFuY2VfZGI=
  SECRET_KEY: Y2hhbmdlX3RoaXNfc2VjcmV0
  REDIS_URL: cmVkaXM6Ly9yZWRpczo2Mzc5LzA=
  SENTRY_DSN: aHR0cHM6Ly9leGFtcGxlQGV4YW1wbGUuaW5nZXN0LnNlbnRyeS5pby8x
